apiVersion: v1
kind: Pod
metadata:
  name: log
spec:
  containers:
    - name: l1
      image: quay.io/mvala/dummylogger:latest
      command:
        - "/dummylogger"
      args:
        - "-loginterval=1500"
        - "-file=/root/log/l1.log"
      volumeMounts:
        - mountPath: "/root/log"
          name: log-storage
    - name: l2
      image: quay.io/mvala/dummylogger:latest
      command:
        - "/dummylogger"
      args:
        - "-loginterval=1000"
        - "-file=/root/log/l2.log"
      volumeMounts:
        - mountPath: "/root/log"
          name: log-storage
#    - name: collector
#      image: quay.io/mvala/logcollector:latest
#      command:
#        - "/go/bin/collector"

  volumes:
    - name: log-storage
      persistentVolumeClaim:
       claimName: pvc01
