apiVersion: v1
kind: Pod
metadata:
  name: log
spec:
  containers:
  - name: l1
    image: quay.io/mvala/dummylogger:latest
    command:
      - "/dummylogger"
    args:
      - "-loginterval=1500"
  - name: l2
    image: quay.io/mvala/dummylogger:latest
    command:
      - "/dummylogger"
    args:
      - "-loginterval=1000"
